#! /bin/sh

setxkbmap fr -variant ergol

bspc config border_width         0
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config initial_polarity          second_child

bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a nvim-float state=floating rectangle=1000x200+460+950

# Natural scrolling
xinput set-prop "DELL0CA9:00 27C6:0D53 Mouse" "libinput Natural Scrolling Enabled" 1
xinput set-prop "DELL0CA9:00 27C6:0D53 Touchpad" "libinput Natural Scrolling Enabled" 1

# Keyboard rate
xset r rate 300 50


## Autostart ##

run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}

# run feh --bg-scale ~/dotfiles/themes/wallpapers/main.jpg
run xsetroot -solid "#7797cc"

run sxhkd

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 0.1; done

external_monitor=$(xrandr --query | grep 'HDMI-A-0')
if [[ $external_monitor = *connected* ]]; then
    xrandr \
      --output HDMI-A-0 --primary --mode 1920x1080 --pos 0x-500 --rotate normal \
      --output eDP --mode 1920x1200 --pos -1920x0 --rotate inverted
    bspc monitor "HDMI-A-0" -d 1 2 3 4 6 7 8 9
    bspc monitor "eDP" -d 5
    MONITOR=HDMI-A-0 polybar main &
    MONITOR=eDP polybar external &
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
    polybar main &
fi
