[global]
progress_full_character = "="
progress_empty_character = "="
progress_prefix = "["
progress_suffix = "]"
time_format = "%Y-%m-%d %H:%M:%S"

[banner]
color = "red"
command = "echo \"std : : main\" | figlet -f slant"

# [docker]
# Local containers MUST start with a slash
# https://github.com/moby/moby/issues/6705
# "/nextcloud-nextcloud-1" = "Nextcloud"
# "/nextcloud-nextcloud-mariadb-1" = "Nextcloud Database"

[uptime]
prefix = "Up"

[filesystems]
root = "/"

[memory]
swap_pos = "beside" # or "below" or "none"

# [fail_2_ban]
# jails = ["sshd", "anotherjail"]

[last_login]
moi = 2
